Repository ontohub/ontohub-models, pull requests merged in 2018-02, with the labels that each got.

#159 Drop DB functions in migration if they exist
  db/migrate/20160902111740_initial_schema.rb
Labels: ready for review

#161 Simplify rubocop config.
  .rubocop.yml
  .rubocop_disabled.yml
  .rubocop_enabled.yml
  .rubocop_modified.yml
  app/models/repository.rb
  db/migrate/20160902111740_initial_schema.rb
  lib/ontohub-models.rb
Labels: in review

#160 Add git shell API keys
  app/models/api_key.rb
  app/models/git_shell_api_key.rb
  app/models/hets_api_key.rb
  db/migrate/20160902111740_initial_schema.rb
  spec/factories/api_keys_factory.rb
  spec/factories/public_keys_factory.rb
  spec/models/git_shell_api_key_spec.rb
  spec/models/hets_api_key_spec.rb
  spec/shared_examples/an_api_key.rb
Labels: approved
